<?

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


namespace App\Http\Models;

interface Model {
    /**
     * @return array An array representation of this model.
     */
    public function toArray() : array;

    /**
     * Populates this model with data provided in an array.
     *
     * @param array $arr Array with model data.
     */
    public function fromArray(array $arr);
}
